version: '3.8'

services:
  daven-iori-frontend:
    image: daven-iori-frontend:latest
    container_name: daven-iori-frontend
    build: .
    restart: unless-stopped
    networks:
      - web
    labels:
      # Habilita o Traefik para este serviço
      - "traefik.enable=true" # --- Roteador principal para HTTPS ---
      - "traefik.http.routers.daven-iori-frontend.rule=Host(`daveniori.com.br`)"
      - "traefik.http.routers.daven-iori-frontend.service=daven-iori-frontend"
      - "traefik.http.routers.daven-iori-frontend.entrypoints=websecure"
      - "traefik.http.routers.daven-iori-frontend.tls=true"
      - "traefik.http.routers.daven-iori-frontend.tls.certresolver=lets-encrypt"

      # --- Serviço (aponta para a porta interna do contêiner) ---
      - "traefik.http.services.daven-iori-frontend.loadbalancer.server.port=80"

networks:
  web:
    external: true
